### ISSUE TITLE
The problem with visualization during inference

### ISSUE THREAD

**Issue by wujiang0156** [dyzy41/ChangeCLIP#6]
Your algorithm proposed in the paper is a fantastic idea. However, I have a few questions to ask you. When I use the ChangeCLIP_best_weights you provided to visualize the inference results of images in the test directory of datasets like LEVIR, I found the results to be unsatisfactory. Why are my visualization results so poor? Looking forward to your reply.
                                         GT:
![gt](https://github.com/dyzy41/ChangeCLIP/assets/7938373/7838afd3-13ac-4986-a1d9-b495607afefa)

                                        predict
![pred](https://github.com/dyzy41/ChangeCLIP/assets/7938373/a3e27a2a-37a8-4e98-9e86-2d03617aa7c9)

This is my code：
    parser.add_argument('--file_list', default='D:/pythonwork/Data/LEVIR-CD/LEVIR-CD256256CLIP/test.txt', help='Image file')
    parser.add_argument('--config', default='configs/0cd_ce/changeclip_levir.py')
    parser.add_argument('--checkpoint', default='checkpoint/best_mIoU_iter_17000.pth')

 Could you please share the visualization process and code you used? Thank you.

**Comment by dyzy41** [comment]
I guess the size of your input image is wrong. In fact, the input size should be 256x256. The inference method I designed in the paper is as follows:
(1) First, divide the large image of the test set into 256x256 according to the splitting method of the training set.
(2) Perform inference on slices and obtain inference results
(3) The inference results are spliced and integrated into a large picture, and the accuracy obtained is the accuracy mentioned in the article.
In addition, in the config file of the code, there is configs/0cd_ce/changeclip_levir_test.py, line71, test_cfg=dict(mode='slide', crop_size=(256, 256), stride=(128, 128)). If you input a large image directly and follow the sliding window prediction provided by mmseg, you will get better accuracy indicators.

**Comment by wujiang0156** [comment]
Thank you for your reply. In fact, I divided the large images in the test set into small blocks of 256x256 and performed inference on these slices. If the inference results of the slices are not good, then stitching them into a large image will certainly not be good either. However, I did not use overlapping slices for inference. Could this be the problem? I will try to perform inference with overlapping slices. @dyzy41

**Comment by dyzy41** [comment]
You can try this config.py for test, configs/0cd_ce/changeclip_levir_test.py

**Comment by wujiang0156** [comment]
@dyzy41 
Thank you for your reply.  
I used changeclip_levir_test.py for testing, and indeed, the results were better than my previous ones. 

Additionally, I have an annother question: Did you use the same number of training epochs for your comparative experiments? For example, did you use 40k epochs for your method and also 40k epochs for Changerformer? Or did you follow the number of epochs set by each paper for comparison? The number of training epochs can affect accuracy, and if the training epochs are different for comparison, there may be differences in the results. How did you set the epochs for other methods?
 Looking forward to your reply, thank you very much.

**Comment by dyzy41** [comment]
"When training a model, if you find that the loss has converged, you can stop the training. I trained the model in this way."

**Comment by COUJIALUO** [comment]
"Hello, I'd like to know how you managed to get the prediction code to work, as I've set the parameters the same as yours, but I encountered an error during prediction."
Traceback (most recent call last):
  File "/root/autodl-tmp/ChangeCLIP-release/tools/infer_folderCD.py", line 72, in <module>
    main()
  File "/root/autodl-tmp/ChangeCLIP-release/tools/infer_folderCD.py", line 64, in main
    results = model.test_step(data)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/ChangeCLIP-release/mmseg/models/segmentors/base.py", line 96, in forward
    return self.predict(inputs, data_samples)
  File "/root/autodl-tmp/ChangeCLIP-release/mmseg/models/segmentors/ChangeCLIPCD.py", line 514, in predict
    seg_logits = self.inference(inputs, batch_img_metas)
  File "/root/autodl-tmp/ChangeCLIP-release/mmseg/models/segmentors/ChangeCLIPCD.py", line 747, in inference
    seg_logit = self.whole_inference(inputs, batch_img_metas)
  File "/root/autodl-tmp/ChangeCLIP-release/mmseg/models/segmentors/ChangeCLIPCD.py", line 718, in whole_inference
    seg_logits = self.encode_decode(inputs, batch_img_metas)
  File "/root/autodl-tmp/ChangeCLIP-release/mmseg/models/segmentors/ChangeCLIPCD.py", line 219, in encode_decode
    textA, textB = self.get_cls_text(batch_img_metas, False)
  File "/root/autodl-tmp/ChangeCLIP-release/mmseg/models/segmentors/ChangeCLIPCD.py", line 388, in get_cls_text
    foreA = ', '.join(['remote sensing image foreground objects']+img_infos[i]['jsonA'])
KeyError: 'jsonA'

**Comment by COUJIALUO** [comment]
@wujiang0156

**Comment by wujiang0156** [comment]
@COUJIALUO 
Just predict according to the method provided by the authors above.

**Comment by cpwu6628** [comment]
I found that my prediction graph is completely black during testing. Moreover, I found that there is a significant difference between the testing metrics after training and when testing with a separate test file. Have you encountered this problem?

**Comment by wujiang0156** [comment]
I have not encountered this issue. You need to carefully reproduce the results according to the author's original implementation.

**Comment by dyzy41** [comment]
@cpwu6628 Usually, model training does not go wrong; the issue you're encountering should be checked in detail to see if the data is correct. For example, are the labels 0/1 or 0/255? The metrics displayed during training are on the validation set, while the metrics displayed during individual testing are on the test set.

**Comment by M2WindRunner** [comment]
Truth be told, I'm also having problems with all the prediction charts turning all black. The test statement I used was the one mentioned by the author in train.sh. The test results on different datasets are all black.

**Comment by cpwu6628** [comment]
Excuse me, have you resolved this issue now?

**Comment by ysh2088** [comment]
> 请问这个问题现在解决了吗？
> […](#)

我也有这样的问题，请问您解决了吗
